### PR TITLE
Upgradation of cities-with-1000 dependency

### PR DESCRIPTION
**Pull request by nabilashraf**
- `cities-with-1000` bumped to v1.0.4
- cities.pbf built with latest file from geonames.org

### CODE REVIEW

**Comment by zeke** [comment]
Out of curiosity, what are you using this module for?  Anything fun?

**Comment by nabilashraf** [comment]
I used this for a client of mine who wanted to have population and Geospatial data available when someone queries a radius search for all the regions close to them for weather conditions. But it can be used in much more, I believe if the module can be linked directly with geonames api / etc to always get latest data and we don't have to build multiple times. And config to adjust fields that are received. Probably have to rewrite the module in that sense but that could be something.

**Comment by zeke** [comment]
That sounds interesting. This could be a good use case for the "serverless" lambda functions using something like https://functions.netlify.com

**Comment by nabilashraf** [comment]
Totally. Let's share some ideas to move this module to a serverless model. What do you think?

**Comment by zeke** [comment]
I think this module can remain what it is without changes. It works well in Node.js environments.

The serverless project could be a separate repo that depends on this module for data, but is designed for browser-based apps that need to make one-off requests for city data.

**Comment by nabilashraf** [comment]
Makes perfect sense. Do you want to create a repo or should I?

**Comment by zeke** [comment]
Go for it. Feel free to invite me to follow along, review PRs, etc

**Comment by zeke** [comment]
Hey @nabilashraf 👋🏼 

I ended up publishing my `nearby-cities` module as a Netlify function. Thought you might like to know.

See https://github.com/zeke/nearby-cities#online-usage

Example query: https://nearby-cities.netlify.app/.netlify/functions/search?latitude=37.871593&longitude=-122.272743

**Comment by nabilashraf** [comment]
> Hey @nabilashraf 👋🏼 
> 
> I ended up publishing my `nearby-cities` module as a Netlify function. Thought you might like to know.
> 
> See https://github.com/zeke/nearby-cities#online-usage
> 
> Example query: https://nearby-cities.netlify.app/.netlify/functions/search?latitude=37.871593&longitude=-122.272743

This is so cool @zeke. Sorry I couldn't start earlier, can we have an option to choose the population factor, that will make this function a wholesome experience. I believe the population factor was what had been asked a lot.

But anyways cheers man for this wonderful package! 🥳

**Pull request merged**
